name: Linux

on: [push]

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
      fail-fast: false
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - run: conda --version

      - name: Install python dependencies (pip)
        run: |
          pip install --upgrade pip
          conda install arviz pystan -c conda-forge

      - name: RStan, PyStan and ArviZ versions
        run: |
          python -c "import arviz;print('ArviZ version: {}'.format(arviz.__version__))"
          python -c "import pystan;print('PyStan version: {}'.format(pystan.__version__))"

      - name: PyStan speed test
        run: |
          python run_PyStan.py

      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: PyStan_results
          path: ./results
